In [42]:
# Import the dependencies.
from pathlib import Path
from sqlalchemy import create_engine, text, Column, Integer, String, Date
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session
import pandas as pd
from sklearn import tree
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

# Needed for decision tree visualization
import pydotplus
from IPython.display import Image

### Load and Preprocess Data

In [43]:
# Load student data
def LoadData():
    #Load PostGres database
    userName = "postgres"
    password = "postgres" #use your postgres password if you changed it
    database = "MLearning" 
    engine = create_engine(f"postgresql+psycopg2://{userName}:{password}@localhost:5432/{database}")
    conn = engine.connect()

    #Pull the data into pandas. We are filtering by the period    
    try:
        # Query All Records in the the Database
        query = text("SELECT * FROM Student_Data")
        student_df = pd.read_sql(query, conn)
        
    except:
        print("No data Available")
        
    return student_df

In [44]:
# Create a base class for declarating class definitions to produce Table objects
Base = declarative_base()

In [45]:
class Student(Base):
    __tablename__ = "Student_Data"
    
    Gender  = Column(String),
    Age = Column(String),
    Education_Level = Column(String),
    Institution_Type = Column(String),
    IT_Student = Column(String),
    Student_Location = Column(String),
    Load_Shedding = Column(String),
    Financial_Condition = Column(String),
    Internet_Type = Column(String),
    Network_Type = Column(String),
    Class_Duration = Column(String),
    Self_Lms = Column(String),
    Device = Column(String),
    Adaptivity_Level = Column(String),
    Student_ID = Column(Integer, primary_key = True)

/var/folders/tx/sr99h3gn7plb88mpxvnnnj3m0000gn/T/ipykernel_8170/3987325553.py:1: SAWarning: Ignoring declarative-like tuple value of attribute 'Gender': possibly a copy-and-paste error with a comma accidentally placed at the end of the line?
  class Student(Base):
/var/folders/tx/sr99h3gn7plb88mpxvnnnj3m0000gn/T/ipykernel_8170/3987325553.py:1: SAWarning: Ignoring declarative-like tuple value of attribute 'Age': possibly a copy-and-paste error with a comma accidentally placed at the end of the line?
  class Student(Base):
/var/folders/tx/sr99h3gn7plb88mpxvnnnj3m0000gn/T/ipykernel_8170/3987325553.py:1: SAWarning: Ignoring declarative-like tuple value of attribute 'Education_Level': possibly a copy-and-paste error with a comma accidentally placed at the end of the line?
  class Student(Base):
/var/folders/tx/sr99h3gn7plb88mpxvnnnj3m0000gn/T/ipykernel_8170/3987325553.py:1: SAWarning: Ignoring declarative-like tuple value of attribute 'Institution_Type': possibly a copy-and-paste error with

In [46]:
# Load into dataframe
student_df = LoadData()
student_df = student_df.rename(columns={"adaptivity_level": "adaptability_level"})

In [47]:
# Drop network_type column 
student_df = student_df.drop(['network_type'], axis=1)
student_df = student_df.drop(['student_id'], axis=1)
student_df.head()

gender    age education_level institution_type it_student student_location  \
0    Boy  21-25      University   Non Government         No              Yes   
1   Girl  21-25      University   Non Government         No              Yes   
2   Girl  16-20         College       Government         No              Yes   
3   Girl  11-15          School   Non Government         No              Yes   
4   Girl  16-20          School   Non Government         No              Yes   

  load_shedding financial_condition internet_type class_duration self_lms  \
0           Low                 Mid          Wifi            3-6       No   
1          High                 Mid   Mobile Data            1-3      Yes   
2           Low                 Mid          Wifi            1-3       No   
3           Low                 Mid   Mobile Data            1-3       No   
4           Low                Poor   Mobile Data              0       No   

   device adaptability_level  
0     Tab           Moderate  
1  Mobile           Moderate  
2  Mobile           Moderate  
3  Mobile           Moderate  
4  Mobile                Low

### `Value Counts` for Each Feature

In [48]:
student_df['financial_condition'].value_counts()

Mid     878
Poor    242
Rich     85
Name: financial_condition, dtype: int64

In [49]:
student_df['gender'].value_counts()

Boy     663
Girl    542
Name: gender, dtype: int64

In [50]:
student_df['age'].value_counts()

21-25    374
11-15    353
16-20    278
1-5       81
26-30     68
6-10      51
Name: age, dtype: int64

In [51]:
student_df['education_level'].value_counts()

School        530
University    456
College       219
Name: education_level, dtype: int64

In [52]:
student_df['institution_type'].value_counts()

Non Government    823
Government        382
Name: institution_type, dtype: int64

In [53]:
student_df['student_location'].value_counts()

Yes    935
No     270
Name: student_location, dtype: int64

In [54]:
student_df['internet_type'].value_counts()

Mobile Data    695
Wifi           510
Name: internet_type, dtype: int64

In [55]:
student_df['class_duration'].value_counts()

1-3    840
3-6    211
0      154
Name: class_duration, dtype: int64

In [56]:
student_df['device'].value_counts()

Mobile      1013
Computer     162
Tab           30
Name: device, dtype: int64

In [57]:
student_df['adaptability_level'].value_counts()

Moderate    625
Low         480
High        100
Name: adaptability_level, dtype: int64

In [58]:
student_df['load_shedding'].value_counts()

Low     1004
High     201
Name: load_shedding, dtype: int64

### Save Cleaned DF to CSV

In [59]:
# Export clean dataframe to csv
student_df.to_csv("Resources/StudentAdaptabilityClean.csv")

### Encode the categorical variables from the features data using `get_dummies`

In [60]:
# Define your features (X) and target (y)
X = student_df.copy()
X = X.drop(columns=['adaptability_level'])
y = student_df["adaptability_level"].ravel()
X = pd.get_dummies(X)
student_df["adaptability_level"].unique()

array(['Moderate', 'Low', 'High'], dtype=object)

### Separate the features `train` and `test` sets

In [61]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=300)

### Scale the data using `StandardScaler`

In [62]:
#Create a StandardScaler instances
scaler = StandardScaler()

#Fit the StandardScaler
X_scaler = scaler.fit(X_train)

#Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

### Fitting the Random Forest Model

In [63]:
from sklearn.ensemble import RandomForestClassifier
# Create a random forest classifier
rf_model = RandomForestClassifier(n_estimators=2000, random_state=300)

In [64]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

### Make predictions using the `Random Forest Algorithm`

In [65]:
# Making predictions using the testing data
y_pred = rf_model.predict(X_test_scaled)

# Review predictions
y_pred[:5]

array(['Moderate', 'Low', 'Moderate', 'Low', 'Moderate'], dtype=object)

### Model Evaluation

In [66]:
conf_matrix = confusion_matrix(y_test, y_pred)

In [67]:
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[ 17   0   5]
 [  2 105  12]
 [  1  10 150]]


In [68]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}%".format(accuracy * 100))

Accuracy: 90.07%


In [69]:
from sklearn.metrics import precision_score, recall_score, f1_score

# Assuming you have the true labels (y_true) and predicted labels (y_pred)
# Replace y_true and y_pred with your actual data.

# Calculate precision
precision = precision_score(y_test, y_pred, average='weighted')  # 'weighted' takes class imbalance into account
print("Precision: {:.2f}".format(precision))

# Calculate recall
recall = recall_score(y_test, y_pred, average='weighted')  # 'weighted' takes class imbalance into account
print("Recall: {:.2f}".format(recall))

# Calculate F1-score
f1 = f1_score(y_test, y_pred, average='weighted')  # 'weighted' takes class imbalance into account
print("F1-score: {:.2f}".format(f1))


Precision: 0.90
Recall: 0.90
F1-score: 0.90


### Print Classification Report

In [70]:
print("Classification Report")
print(classification_report(y_test, y_pred))

Classification Report
              precision    recall  f1-score   support

        High       0.85      0.77      0.81        22
         Low       0.91      0.88      0.90       119
    Moderate       0.90      0.93      0.91       161

    accuracy                           0.90       302
   macro avg       0.89      0.86      0.87       302
weighted avg       0.90      0.90      0.90       302



### Use the `RandomOverSampler` module from the imbalanced-learn library to resample the data

This step will be needed in order to balance the dataset. Based on the classification report above, the ratio of High to Low/Moderate is imbalanced, resulting in decreased precision for predicting this class. 

In [71]:
# Import the RandomOverSampler module form imbalanced-learn
from imblearn.over_sampling import RandomOverSampler

# Instantiate the random oversampler model
oversample_rf_model = RandomOverSampler(random_state=300)
oversample_rf_model 

# Fit the original training data to the random_oversampler model
X_resampled, y_resampled = oversample_rf_model.fit_resample(X, y)

# Split into training and testing sets
X_train2, X_test2, y_train2, y_test2 = train_test_split(X_resampled, y_resampled, random_state=300)

In [72]:
#Create a StandardScaler instances
scaler2 = StandardScaler()

# Fit the StandardScaler
X_scaler2 = scaler2.fit(X_train2)

# Scale the data
X_train_scaled2 = X_scaler2.transform(X_train2)
X_test_scaled2 = X_scaler2.transform(X_test2)

In [73]:
import numpy as np
# Count the distinct values of the resampled labels data
unique_values, counts = np.unique(y_resampled, return_counts=True)
counts

array([625, 625, 625])

### Fitting the Random Forest Model Using the Resampled Data

In [74]:
from sklearn.ensemble import RandomForestClassifier
# Create a random forest classifier
oversample_rf_model = RandomForestClassifier(n_estimators=2000, random_state=300)

# Fitting the model
oversample_rf_model.fit(X_resampled, y_resampled)

RandomForestClassifier(n_estimators=2000, random_state=300)

### Make predictions with the resampled data using the Random Forest model

In [75]:
# Making predictions using the testing data
oversample_y_pred = oversample_rf_model.predict(X_test2)

# Review predictions
oversample_y_pred[:5]

array(['Moderate', 'High', 'Moderate', 'Moderate', 'High'], dtype=object)

In [76]:
# Print the balanced_accuracy score of the model 
accuracy_score(y_test2, oversample_y_pred)

0.8955223880597015

In [99]:
# Generate a confusion matrix for the model
cf_matrix = confusion_matrix(y_test2, oversample_y_pred)
cf_matrix

array([[161,   0,   0],
       [ 10, 120,  10],
       [ 21,   8, 139]])

In [103]:
# Print classification report
new_report = classification_report(y_test2, oversample_y_pred)
print(new_report)

              precision    recall  f1-score   support

        High       0.84      1.00      0.91       161
         Low       0.94      0.86      0.90       140
    Moderate       0.93      0.83      0.88       168

    accuracy                           0.90       469
   macro avg       0.90      0.89      0.89       469
weighted avg       0.90      0.90      0.89       469

