In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Dense
from keras.callbacks import ModelCheckpoint
import numpy as np
#  Import and read the charity_data.csv.
import pandas as pd 
student_df  = pd.read_csv('Resources/students_adaptability.csv')
student_df.head()


ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
# Determine the number of unique values in each column.
unique_value_counts = student_df.nunique()
print(unique_value_counts)

Gender                 2
Age                    6
Education Level        3
Institution Type       2
IT Student             2
Location               2
Load-shedding          2
Financial Condition    3
Internet Type          2
Network Type           3
Class Duration         3
Self Lms               2
Device                 3
Adaptivity Level       3
dtype: int64


In [ ]:
# Define your features (X) and target (y)
X = student_df.copy()
X = X.drop(columns=['Adaptivity Level'])
y = student_df["Adaptivity Level"].ravel()
X = pd.get_dummies(X)

In [ ]:

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=70)

In [ ]:
#Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
# Create a random forest classifier
rf_model = RandomForestClassifier(n_estimators=500, random_state=78)

In [ ]:

# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [ ]:

# Making predictions using the testing data
y_pred = rf_model.predict(X_test_scaled)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
# y_pred = rf_model.predict(X_test)
conf_matrix = confusion_matrix(y_test, y_pred)

c:\Users\Sujatha\anaconda3\envs\dev\lib\site-packages\sklearn\base.py:432: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


In [ ]:
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[  0   3  21]
 [  0  56  66]
 [  0   9 147]]


In [ ]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}%".format(accuracy * 100))


Accuracy: 67.22%
