In [44]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Dense
from keras.callbacks import ModelCheckpoint
import numpy as np
#  Import and read the charity_data.csv.
import pandas as pd 
student_df  = pd.read_csv('Resources/students_adaptability.csv')
student_df.head()


Gender    Age Education Level Institution Type IT Student Location  \
0    Boy  21-25      University   Non Government         No      Yes   
1   Girl  21-25      University   Non Government         No      Yes   
2   Girl  16-20         College       Government         No      Yes   
3   Girl  11-15          School   Non Government         No      Yes   
4   Girl  16-20          School   Non Government         No      Yes   

  Load-shedding Financial Condition Internet Type Network Type Class Duration  \
0           Low                 Mid          Wifi           4G            3-6   
1          High                 Mid   Mobile Data           4G            1-3   
2           Low                 Mid          Wifi           4G            1-3   
3           Low                 Mid   Mobile Data           4G            1-3   
4           Low                Poor   Mobile Data           3G              0   

  Self Lms  Device Adaptivity Level  
0       No     Tab         Moderate  
1      Yes  Mobile         Moderate  
2       No  Mobile         Moderate  
3       No  Mobile         Moderate  
4       No  Mobile              Low

In [45]:
# Determine the number of unique values in each column.
unique_value_counts = student_df.nunique()
print(unique_value_counts)

Gender                 2
Age                    6
Education Level        3
Institution Type       2
IT Student             2
Location               2
Load-shedding          2
Financial Condition    3
Internet Type          2
Network Type           3
Class Duration         3
Self Lms               2
Device                 3
Adaptivity Level       3
dtype: int64


In [46]:
# Define your features (X) and target (y)
X = student_df.copy()
X = X.drop(columns=['Adaptivity Level'])
y = student_df["Adaptivity Level"].ravel()
X = pd.get_dummies(X)
student_df["Adaptivity Level"].unique()

array(['Moderate', 'Low', 'High'], dtype=object)

In [47]:

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=70)

In [48]:
#Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [49]:
from sklearn.ensemble import RandomForestClassifier
# Create a random forest classifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=78)

In [50]:

# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [51]:

# Making predictions using the testing data
y_pred = rf_model.predict(X_test_scaled)

In [52]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
# y_pred = rf_model.predict(X_test)
conf_matrix = confusion_matrix(y_test, y_pred)

In [53]:
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[ 17   0   7]
 [  2 109  11]
 [  4   9 143]]


In [54]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}%".format(accuracy * 100))


Accuracy: 89.07%


In [55]:
from sklearn.metrics import precision_score, recall_score, f1_score

# Assuming you have the true labels (y_true) and predicted labels (y_pred)
# Replace y_true and y_pred with your actual data.

# Calculate precision
precision = precision_score(y_test, y_pred, average='weighted')  # 'weighted' takes class imbalance into account
print("Precision: {:.2f}".format(precision))

# Calculate recall
recall = recall_score(y_test, y_pred, average='weighted')  # 'weighted' takes class imbalance into account
print("Recall: {:.2f}".format(recall))

# Calculate F1-score
f1 = f1_score(y_test, y_pred, average='weighted')  # 'weighted' takes class imbalance into account
print("F1-score: {:.2f}".format(f1))


Precision: 0.89
Recall: 0.89
F1-score: 0.89
